/**
 * waste-data.js
 * Comprehensive data module for the AI Waste Classification System.
 * Maps MobileNet/ImageNet classes → waste categories and provides
 * recycling instructions, environmental impact stats, and eco-tips.
 */

// ─── Waste Categories ───────────────────────────────────────────
const CATEGORIES = {
  plastic: {
    id: 'plastic',
    name: 'Plastic',
    icon: '♻️',
    emoji: '🧴',
    color: '#00b4d8',
    gradient: 'linear-gradient(135deg, #0077b6, #00b4d8)',
    description: 'Plastic items including bottles, containers, packaging, and bags.',
  },
  glass: {
    id: 'glass',
    name: 'Glass',
    icon: '🫙',
    emoji: '🍾',
    color: '#7209b7',
    gradient: 'linear-gradient(135deg, #560bad, #7209b7)',
    description: 'Glass bottles, jars, containers, and window glass.',
  },
  metal: {
    id: 'metal',
    name: 'Metal',
    icon: '🥫',
    emoji: '🔩',
    color: '#f72585',
    gradient: 'linear-gradient(135deg, #b5179e, #f72585)',
    description: 'Metal cans, aluminum foil, tin containers, and scrap metal.',
  },
  organic: {
    id: 'organic',
    name: 'Organic',
    icon: '🍂',
    emoji: '🌿',
    color: '#00d4aa',
    gradient: 'linear-gradient(135deg, #00a884, #00d4aa)',
    description: 'Food waste, yard trimmings, plants, and biodegradable materials.',
  },
  paper: {
    id: 'paper',
    name: 'Paper & Cardboard',
    icon: '📄',
    emoji: '📦',
    color: '#fb8500',
    gradient: 'linear-gradient(135deg, #e76f51, #fb8500)',
    description: 'Newspapers, magazines, cardboard boxes, and office paper.',
  },
  ewaste: {
    id: 'ewaste',
    name: 'E-Waste',
    icon: '💻',
    emoji: '📱',
    color: '#4361ee',
    gradient: 'linear-gradient(135deg, #3a0ca3, #4361ee)',
    description: 'Electronic devices, batteries, cables, and circuit boards.',
  },
  hazardous: {
    id: 'hazardous',
    name: 'Hazardous',
    icon: '⚠️',
    emoji: '☣️',
    color: '#ef233c',
    gradient: 'linear-gradient(135deg, #d90429, #ef233c)',
    description: 'Chemicals, paint, medical waste, and toxic materials.',
  },
  general: {
    id: 'general',
    name: 'General Waste',
    icon: '🗑️',
    emoji: '❓',
    color: '#6c757d',
    gradient: 'linear-gradient(135deg, #495057, #6c757d)',
    description: 'Items that don\'t fit standard recycling categories.',
  },
};

// ─── ImageNet Class → Waste Category Mapping ────────────────────
// Maps MobileNet predicted class names (lowercase) to waste categories.
// Partial matches are supported — the mapper checks if the prediction
// string includes any of these keys.
const CLASS_TO_CATEGORY = {
  // ── Plastic ──
  'water bottle': 'plastic',
  'plastic bag': 'plastic',
  'pop bottle': 'plastic',
  'soda bottle': 'plastic',
  'bottle cap': 'plastic',
  'pill bottle': 'plastic',
  'bucket': 'plastic',
  'pail': 'plastic',
  'pitcher': 'plastic',
  'measuring cup': 'plastic',
  'ladle': 'plastic',
  'crate': 'plastic',
  'container': 'plastic',
  'diaper': 'plastic',
  'nappy': 'plastic',
  'nipple': 'plastic',
  'pacifier': 'plastic',
  'rubber eraser': 'plastic',
  'eraser': 'plastic',
  'sunglasses': 'plastic',
  'sunglass': 'plastic',
  'shower curtain': 'plastic',
  'rain barrel': 'plastic',
  'paintbrush': 'plastic',
  'plunger': 'plastic',
  'toilet seat': 'plastic',
  'mask': 'plastic',
  'ski mask': 'plastic',
  'snorkel': 'plastic',
  'plastic wrap': 'plastic',

  // ── Glass ──
  'wine bottle': 'glass',
  'beer bottle': 'glass',
  'beer glass': 'glass',
  'goblet': 'glass',
  'cocktail shaker': 'glass',
  'red wine': 'glass',
  'whiskey jug': 'glass',
  'glass': 'glass',
  'jar': 'glass',
  'vase': 'glass',
  'perfume': 'glass',
  'hourglass': 'glass',
  'lens': 'glass',
  'magnifying glass': 'glass',
  'window shade': 'glass',
  'mirror': 'glass',
  'snow globe': 'glass',
  'maraca': 'glass',
  'carafe': 'glass',
  'decanter': 'glass',

  // ── Metal ──
  'can opener': 'metal',
  'tin can': 'metal',
  'pop can': 'metal',
  'beer can': 'metal',
  'soup can': 'metal',
  'safety pin': 'metal',
  'screw': 'metal',
  'nail': 'metal',
  'hook': 'metal',
  'chain': 'metal',
  'chainlink fence': 'metal',
  'barbell': 'metal',
  'dumbbell': 'metal',
  'weight': 'metal',
  'wrench': 'metal',
  'hammer': 'metal',
  'screwdriver': 'metal',
  'hatchet': 'metal',
  'cleaver': 'metal',
  'knife': 'metal',
  'letter opener': 'metal',
  'scissors': 'metal',
  'power drill': 'metal',
  'shovel': 'metal',
  'spatula': 'metal',
  'wok': 'metal',
  'frying pan': 'metal',
  'pan': 'metal',
  'pot': 'metal',
  'caldron': 'metal',
  'dutch oven': 'metal',
  'corkscrew': 'metal',
  'thimble': 'metal',
  'combination lock': 'metal',
  'padlock': 'metal',
  'key': 'metal',
  'umbrella': 'metal',
  'shield': 'metal',
  'breastplate': 'metal',
  'cuirass': 'metal',
  'armor': 'metal',
  'helmet': 'metal',
  'bell': 'metal',
  'gong': 'metal',
  'steel drum': 'metal',
  'filing cabinet': 'metal',
  'safe': 'metal',
  'shopping cart': 'metal',
  'wheelbarrow': 'metal',
  'forklift': 'metal',
  'iron': 'metal',
  'waffle iron': 'metal',
  'radiator': 'metal',
  'coil': 'metal',
  'strainer': 'metal',
  'colander': 'metal',
  'buckle': 'metal',
  'zippo': 'metal',
  'lighter': 'metal',
  'coin': 'metal',

  // ── Organic ──
  'banana': 'organic',
  'orange': 'organic',
  'lemon': 'organic',
  'fig': 'organic',
  'pineapple': 'organic',
  'apple': 'organic',
  'strawberry': 'organic',
  'pomegranate': 'organic',
  'granny smith': 'organic',
  'custard apple': 'organic',
  'jackfruit': 'organic',
  'coconut': 'organic',
  'acorn': 'organic',
  'mushroom': 'organic',
  'agaric': 'organic',
  'ear': 'organic',
  'corn': 'organic',
  'broccoli': 'organic',
  'cauliflower': 'organic',
  'cucumber': 'organic',
  'zucchini': 'organic',
  'artichoke': 'organic',
  'pepper': 'organic',
  'bell pepper': 'organic',
  'cardoon': 'organic',
  'spaghetti squash': 'organic',
  'butternut squash': 'organic',
  'acorn squash': 'organic',
  'head cabbage': 'organic',
  'meat loaf': 'organic',
  'pizza': 'organic',
  'burrito': 'organic',
  'hotdog': 'organic',
  'hot dog': 'organic',
  'cheeseburger': 'organic',
  'hamburger': 'organic',
  'french loaf': 'organic',
  'bagel': 'organic',
  'pretzel': 'organic',
  'dough': 'organic',
  'ice cream': 'organic',
  'ice lolly': 'organic',
  'chocolate sauce': 'organic',
  'hay': 'organic',
  'straw': 'organic',
  'potpie': 'organic',
  'trifle': 'organic',
  'guacamole': 'organic',
  'consomme': 'organic',
  'espresso': 'organic',
  'carbonara': 'organic',
  'plate': 'organic',
  'flower pot': 'organic',
  'bouquet': 'organic',
  'daisy': 'organic',
  'sunflower': 'organic',
  'rose': 'organic',
  'rapeseed': 'organic',
  'wood': 'organic',
  'wooden spoon': 'organic',
  'leaf': 'organic',

  // ── Paper / Cardboard ──
  'envelope': 'paper',
  'packet': 'paper',
  'carton': 'paper',
  'cardboard': 'paper',
  'book jacket': 'paper',
  'dust cover': 'paper',
  'comic book': 'paper',
  'crossword puzzle': 'paper',
  'jigsaw puzzle': 'paper',
  'notebook': 'paper',
  'binder': 'paper',
  'paper towel': 'paper',
  'tissue': 'paper',
  'toilet tissue': 'paper',
  'napkin': 'paper',
  'menu': 'paper',
  'letter': 'paper',
  'newspaper': 'paper',
  'magazine': 'paper',
  'brochure': 'paper',
  'postcard': 'paper',
  'poster': 'paper',
  'shopping bag': 'paper',
  'tray': 'paper',
  'matchstick': 'paper',
  'band aid': 'paper',
  'book': 'paper',
  'calendar': 'paper',
  'stationery': 'paper',

  // ── E-Waste ──
  'laptop': 'ewaste',
  'notebook computer': 'ewaste',
  'desktop computer': 'ewaste',
  'monitor': 'ewaste',
  'screen': 'ewaste',
  'television': 'ewaste',
  'tv': 'ewaste',
  'cellular telephone': 'ewaste',
  'cell phone': 'ewaste',
  'cellphone': 'ewaste',
  'smartphone': 'ewaste',
  'ipod': 'ewaste',
  'hand-held computer': 'ewaste',
  'mouse': 'ewaste',
  'keyboard': 'ewaste',
  'space bar': 'ewaste',
  'joystick': 'ewaste',
  'trackball': 'ewaste',
  'remote control': 'ewaste',
  'printer': 'ewaste',
  'modem': 'ewaste',
  'router': 'ewaste',
  'hard disc': 'ewaste',
  'hard drive': 'ewaste',
  'disk': 'ewaste',
  'cd player': 'ewaste',
  'tape player': 'ewaste',
  'cassette player': 'ewaste',
  'cassette': 'ewaste',
  'speaker': 'ewaste',
  'loudspeaker': 'ewaste',
  'microphone': 'ewaste',
  'headphone': 'ewaste',
  'earphone': 'ewaste',
  'projector': 'ewaste',
  'camera': 'ewaste',
  'digital watch': 'ewaste',
  'digital clock': 'ewaste',
  'calculator': 'ewaste',
  'abacus': 'ewaste',
  'electric fan': 'ewaste',
  'vacuum': 'ewaste',
  'washing machine': 'ewaste',
  'dishwasher': 'ewaste',
  'refrigerator': 'ewaste',
  'toaster': 'ewaste',
  'microwave': 'ewaste',
  'electric guitar': 'ewaste',
  'switch': 'ewaste',
  'plug': 'ewaste',
  'power cord': 'ewaste',
  'extension cord': 'ewaste',
  'electric lamp': 'ewaste',
  'lamp': 'ewaste',
  'torch': 'ewaste',
  'flashlight': 'ewaste',
  'solar dish': 'ewaste',
  'photocopier': 'ewaste',
  'scanner': 'ewaste',

  // ── Hazardous ──
  'syringe': 'hazardous',
  'medicine chest': 'hazardous',
  'medicine cabinet': 'hazardous',
  'pill': 'hazardous',
  'drug': 'hazardous',
  'gas pump': 'hazardous',
  'fuel': 'hazardous',
  'oil filter': 'hazardous',
  'paintcan': 'hazardous',
  'paint can': 'hazardous',
  'torch (fire)': 'hazardous',
  'fire extinguisher': 'hazardous',
  'candle': 'hazardous',
  'matchbox': 'hazardous',
  'cartridge': 'hazardous',
  'bullet': 'hazardous',
  'rifle': 'hazardous',
  'revolver': 'hazardous',
  'assault rifle': 'hazardous',
  'bomb': 'hazardous',
  'missile': 'hazardous',
  'warplane': 'hazardous',
  'tank': 'hazardous',
  'mortar': 'hazardous',
  'battery': 'hazardous',
  'car battery': 'hazardous',
  'motor oil': 'hazardous',
  'pesticide': 'hazardous',
  'bleach': 'hazardous',
  'acid': 'hazardous',
  'aerosol': 'hazardous',
  'spray can': 'hazardous',
};

// ─── Recycling Instructions ─────────────────────────────────────
const RECYCLING_INSTRUCTIONS = {
  plastic: {
    steps: [
      'Check the resin identification code (♻️ number 1-7) on the bottom',
      'Rinse out any food residue with water',
      'Remove caps and lids (recycle separately if accepted)',
      'Flatten bottles to save space in the bin',
      'Place in your curbside recycling bin (types 1 & 2 widely accepted)',
    ],
    doNot: [
      'Don\'t bag recyclables in plastic bags — they jam sorting machines',
      'Don\'t recycle plastic utensils, straws, or styrofoam curbside',
      'Don\'t include items smaller than a credit card',
    ],
    tips: [
      'Types 1 (PET) and 2 (HDPE) are the most widely recycled plastics',
      'Soft plastics (bags, wrap) can be returned to grocery store drop-offs',
      'Consider switching to reusable containers to reduce plastic use',
    ],
  },
  glass: {
    steps: [
      'Rinse the glass container to remove food residue',
      'Remove metal lids and caps (recycle separately as metal)',
      'Do NOT break the glass — keep it intact for recycling',
      'Sort by color if your area requires it (clear, green, brown)',
      'Place in the designated glass recycling bin',
    ],
    doNot: [
      'Don\'t include window glass, mirrors, or ceramics — different melting points',
      'Don\'t recycle drinking glasses, pyrex, or crystal',
      'Don\'t include light bulbs (take to special collection)',
    ],
    tips: [
      'Glass can be recycled endlessly without losing quality',
      'Recycling glass reduces CO₂ emissions by 50% vs. new production',
      'One recycled glass bottle saves enough energy to power a bulb for 4 hours',
    ],
  },
  metal: {
    steps: [
      'Rinse cans and containers to remove food residue',
      'Crush aluminum cans to save space (optional)',
      'Keep steel and aluminum together — sorting machines separate them',
      'Include clean aluminum foil and trays',
      'Place in your curbside recycling bin',
    ],
    doNot: [
      'Don\'t include aerosol cans that aren\'t fully empty',
      'Don\'t recycle paint cans with dried paint (hazardous waste)',
      'Don\'t include electronics or appliances curbside',
    ],
    tips: [
      'Recycling aluminum saves 95% of energy vs. making new aluminum',
      'A recycled aluminum can returns as a new can in just 60 days',
      'Steel is the most recycled material in the world',
    ],
  },
  organic: {
    steps: [
      'Collect food scraps in a kitchen compost bin or bag',
      'Include fruit/vegetable peels, coffee grounds, eggshells, and tea bags',
      'Add yard waste like leaves, grass clippings, and small branches',
      'Turn or aerate your compost regularly if home composting',
      'Use municipal green bin if available for curbside composting',
    ],
    doNot: [
      'Don\'t compost meat, dairy, or oily foods in home compost (attracts pests)',
      'Don\'t add diseased plants or treated wood',
      'Don\'t include pet waste in food compost',
    ],
    tips: [
      'Composting reduces landfill methane — a greenhouse gas 80× worse than CO₂',
      'Home compost creates nutrient-rich soil in 2-6 months',
      'Food waste accounts for ~30% of what we throw away',
    ],
  },
  paper: {
    steps: [
      'Keep paper clean and dry — wet paper can\'t be recycled',
      'Flatten cardboard boxes to save space',
      'Remove tape, labels, and staples when possible',
      'Shredded paper should go in a paper bag (too small for sorting machines loose)',
      'Place in your curbside recycling bin',
    ],
    doNot: [
      'Don\'t recycle paper towels, tissues, or napkins (these are compostable)',
      'Don\'t include wax-coated or foil-lined paper (juice boxes vary by area)',
      'Don\'t recycle greasy pizza boxes (compost them instead)',
    ],
    tips: [
      'Recycling one ton of paper saves 17 trees and 7,000 gallons of water',
      'Paper can typically be recycled 5-7 times before fibers are too short',
      'Cardboard is one of the most valuable recyclable materials',
    ],
  },
  ewaste: {
    steps: [
      'Do NOT place e-waste in regular recycling or trash bins',
      'Find a certified e-waste recycler in your area (e.g., e-Stewards, R2)',
      'Back up and wipe personal data before recycling devices',
      'Check manufacturer take-back programs (Apple, Dell, Samsung, etc.)',
      'Use retailer drop-off programs (Best Buy, Staples accept most electronics)',
    ],
    doNot: [
      'Don\'t throw batteries in the trash — risk of fire in waste trucks',
      'Don\'t break open devices — they contain hazardous materials',
      'Don\'t hoard old electronics — recycle them while they still have material value',
    ],
    tips: [
      'One million recycled cell phones yield 35,000 lbs of copper and 75 lbs of gold',
      'Only ~17% of global e-waste is properly recycled',
      'Consider donating working electronics to extend their life',
    ],
  },
  hazardous: {
    steps: [
      'NEVER place hazardous waste in regular trash or recycling',
      'Store in original containers with labels intact',
      'Keep away from children, pets, and heat sources',
      'Locate your nearest hazardous waste collection facility or event',
      'Transport carefully in sealed containers in a ventilated vehicle',
    ],
    doNot: [
      'Don\'t pour chemicals, paint, or oil down drains or storm sewers',
      'Don\'t mix different hazardous materials together',
      'Don\'t burn hazardous waste — releases toxic fumes',
    ],
    tips: [
      'Many communities hold free hazardous waste collection events annually',
      'Latex paint can often be dried out and disposed of with regular trash',
      'Pharmacies often accept unused medications through take-back programs',
    ],
  },
  general: {
    steps: [
      'Check if the item can be donated or repurposed before discarding',
      'Look for specialized recycling programs (textiles, mattresses, etc.)',
      'Break down large items for easier disposal',
      'Place in your regular waste bin if no recycling option exists',
      'Contact your local waste authority for guidance on unusual items',
    ],
    doNot: [
      'Don\'t "wish-cycle" — putting non-recyclables in recycling contaminates the stream',
      'Don\'t dump large items illegally — use scheduled bulk pickup',
      'Don\'t mix waste types — contamination reduces recycling efficiency',
    ],
    tips: [
      'When in doubt, check your local municipality\'s waste sorting guide',
      'Many items can be repaired or upcycled instead of discarded',
      'The best waste is the waste you don\'t create — reduce first!',
    ],
  },
};

// ─── Environmental Impact Data ──────────────────────────────────
const ENVIRONMENTAL_IMPACT = {
  plastic: {
    co2SavedPerKg: 1.5,        // kg CO₂ saved per kg recycled
    energySavedPerKg: 5.77,     // kWh saved per kg recycled
    decompositionTime: '450 years',
    waterSavedPerKg: 180,       // liters
    factoid: 'Recycling 1 plastic bottle saves enough energy to power a laptop for 25 minutes.',
  },
  glass: {
    co2SavedPerKg: 0.67,
    energySavedPerKg: 2.12,
    decompositionTime: '1,000,000 years',
    waterSavedPerKg: 42,
    factoid: 'Glass is 100% recyclable and can be recycled endlessly without loss of quality.',
  },
  metal: {
    co2SavedPerKg: 9.0,
    energySavedPerKg: 14.0,
    decompositionTime: '200-500 years',
    waterSavedPerKg: 40,
    factoid: 'Recycling one aluminum can saves enough energy to run a TV for 3 hours.',
  },
  organic: {
    co2SavedPerKg: 0.5,
    energySavedPerKg: 0.0,
    decompositionTime: '2 weeks - 6 months',
    waterSavedPerKg: 0,
    factoid: 'Composting food waste reduces methane emissions by keeping organics out of landfills.',
  },
  paper: {
    co2SavedPerKg: 0.9,
    energySavedPerKg: 4.0,
    decompositionTime: '2-6 weeks',
    waterSavedPerKg: 26,
    factoid: 'Recycling 1 ton of paper saves 17 trees, 26,000 liters of water, and 2.5 barrels of oil.',
  },
  ewaste: {
    co2SavedPerKg: 2.0,
    energySavedPerKg: 7.0,
    decompositionTime: '1,000+ years',
    waterSavedPerKg: 0,
    factoid: 'The gold in 1 million recycled phones is worth over $34 million.',
  },
  hazardous: {
    co2SavedPerKg: 0.0,
    energySavedPerKg: 0.0,
    decompositionTime: 'Varies (toxic indefinitely)',
    waterSavedPerKg: 0,
    factoid: 'Proper hazardous waste disposal prevents soil and groundwater contamination.',
  },
  general: {
    co2SavedPerKg: 0.1,
    energySavedPerKg: 0.0,
    decompositionTime: 'Varies',
    waterSavedPerKg: 0,
    factoid: 'Reducing waste at the source is the single most effective environmental action.',
  },
};

// ─── Eco Tips (rotating display) ────────────────────────────────
const ECO_TIPS = [
  { tip: 'The average person generates about 4.5 pounds of waste per day.', category: 'general' },
  { tip: 'Only 9% of all plastic ever produced has been recycled.', category: 'plastic' },
  { tip: 'Recycling one aluminum can saves enough energy to listen to a full album on your phone.', category: 'metal' },
  { tip: 'Glass bottles take 1 million years to decompose in a landfill.', category: 'glass' },
  { tip: 'Composting can reduce household waste by up to 30%.', category: 'organic' },
  { tip: 'A single tree can produce enough paper for about 8,333 sheets.', category: 'paper' },
  { tip: 'E-waste represents only 2% of trash in landfills but accounts for 70% of toxic waste.', category: 'ewaste' },
  { tip: 'Improperly disposed batteries can leak toxic chemicals into soil and water.', category: 'hazardous' },
  { tip: 'Buying in bulk can reduce packaging waste by up to 50%.', category: 'general' },
  { tip: 'The Great Pacific Garbage Patch is twice the size of Texas.', category: 'plastic' },
  { tip: 'Recycling steel saves 60% of the energy needed to make new steel.', category: 'metal' },
  { tip: 'One recycled glass jar saves enough energy to watch TV for 3 hours.', category: 'glass' },
  { tip: 'Food waste in landfills generates methane — 80× more potent than CO₂.', category: 'organic' },
  { tip: 'If everyone recycled their newspaper, 250 million trees would be saved annually.', category: 'paper' },
  { tip: 'An old smartphone contains more gold per gram than most gold ore.', category: 'ewaste' },
  { tip: 'The "Reduce, Reuse, Recycle" hierarchy prioritizes reducing waste first.', category: 'general' },
  { tip: 'Plastic bags kill 100,000 marine animals every year.', category: 'plastic' },
  { tip: 'A glass bottle made from recycled glass reduces air pollution by 20%.', category: 'glass' },
  { tip: 'Vermicomposting (using worms) can process food scraps in just 3-6 months.', category: 'organic' },
  { tip: 'Americans use over 60 million plastic water bottles a day — most are not recycled.', category: 'plastic' },
];

// ─── Sample Items for Demo ──────────────────────────────────────
const SAMPLE_ITEMS = [
  { name: 'Plastic Bottle', category: 'plastic', confidence: 0.94 },
  { name: 'Glass Jar', category: 'glass', confidence: 0.91 },
  { name: 'Aluminum Can', category: 'metal', confidence: 0.96 },
  { name: 'Banana Peel', category: 'organic', confidence: 0.89 },
  { name: 'Newspaper', category: 'paper', confidence: 0.93 },
  { name: 'Old Phone', category: 'ewaste', confidence: 0.87 },
];

// ─── Decomposition Timeline Data ────────────────────────────────
const DECOMPOSITION_TIMELINE = [
  { item: 'Banana Peel', time: '2-5 weeks', years: 0.1, category: 'organic' },
  { item: 'Paper Bag', time: '1 month', years: 0.08, category: 'paper' },
  { item: 'Newspaper', time: '6 weeks', years: 0.12, category: 'paper' },
  { item: 'Cardboard', time: '2 months', years: 0.17, category: 'paper' },
  { item: 'Cotton Cloth', time: '5 months', years: 0.42, category: 'general' },
  { item: 'Wood', time: '13 years', years: 13, category: 'organic' },
  { item: 'Tin Can', time: '50 years', years: 50, category: 'metal' },
  { item: 'Aluminum Can', time: '200 years', years: 200, category: 'metal' },
  { item: 'Plastic Bag', time: '500 years', years: 500, category: 'plastic' },
  { item: 'Plastic Bottle', time: '450 years', years: 450, category: 'plastic' },
  { item: 'Glass Bottle', time: '1 million years', years: 1000000, category: 'glass' },
  { item: 'Styrofoam', time: 'Never (non-biodegradable)', years: Infinity, category: 'plastic' },
];

// Expose to window object for non-module script loading
window.CATEGORIES = CATEGORIES;
window.CLASS_TO_CATEGORY = CLASS_TO_CATEGORY;
window.RECYCLING_INSTRUCTIONS = RECYCLING_INSTRUCTIONS;
window.ENVIRONMENTAL_IMPACT = ENVIRONMENTAL_IMPACT;
window.ECO_TIPS = ECO_TIPS;
window.SAMPLE_ITEMS = SAMPLE_ITEMS;
window.DECOMPOSITION_TIMELINE = DECOMPOSITION_TIMELINE;
